In [ ]:
from google.colab import files
uploaded = files.upload()

Saving safeUnsafe.xlsx to safeUnsafe.xlsx


In [ ]:
import pandas as pd
import numpy  as np

In [ ]:

data = pd.read_excel('safeUnsafe.xlsx')
# Dataset is now stored in a Pandas Dataframe

In [ ]:
data


Area                 Zone  ... Is.Bar   Class
0        Ramapuram       Aanandam Nagar  ...     No    Safe
1        Ramapuram       Aanandam Nagar  ...     No    Safe
2        Ramapuram       Aanandam Nagar  ...     No    Safe
3        Ramapuram       Aanandam Nagar  ...     No    Safe
4        Ramapuram          Ambal Nagar  ...     No    Safe
..             ...                  ...  ...    ...     ...
99       Ramapuram  Venkateshwara Nagar  ...     No  Unsafe
100  West Mambalam     Vivekanandapuram  ...     No    Safe
101  West Mambalam     Vivekanandapuram  ...     No    Safe
102  West Mambalam     Vivekanandapuram  ...     No    Safe
103  West Mambalam     Vivekanandapuram  ...     No  Unsafe

[104 rows x 7 columns]

In [ ]:
from sklearn import preprocessing
# create the Labelencoder object
from sklearn.preprocessing import LabelEncoder

area=['Ramapuram','Adyar','West Mambalam']

people=['Low','Medium','High']
police = ['Yes', 'No']
bar=['Yes', 'No']
enc = LabelEncoder().fit(area)
data['Area'] = enc.transform(data['Area'])
zone=['Aanandam Nagar','Ambal Nagar','Amman Nagar','Baktavatsalm Nagar','Chidambaram Nagar','Easwaran Nagar','Gokulam Colony','Kasi Viswanathar Colony','Moogambigai Nagar','Moovendar Colony','Mullai Nagar','Pannerselvam Nagar','Postal Colony','RamaKrishnapuram','Royala Nagar','Sakthi Nagar','Shastri Nagar','South Kesavaperumalpuram','Subramaniam Nagar','Suresh Nagar','Tamil Nagar','Teachers Colony','Thiru Nagar','Venkateshwar Nagar','Venkateshwara Nagar','Vivekanandapuram']
enc1 = LabelEncoder().fit(zone)
data['Zone'] = enc1.transform(data['Zone'])
time=['Morning','Afternoon','Evening','Night']
enc2 = LabelEncoder().fit(time)
data['Time'] = enc2.transform(data['Time'])
enc3 = LabelEncoder().fit(people)
data['People.Frequency'] = enc3.transform(data['People.Frequency'])
enc4 = LabelEncoder().fit(police)
data['Is.Police_Station'] = enc4.transform(data['Is.Police_Station'])
enc5 = LabelEncoder().fit(bar)
data['Is.Bar'] = enc5.transform(data['Is.Bar'])
#print(data['Is.Police_Station'])
#le = preprocessing.LabelEncoder()
#convert the categorical columns into numeric
# data['Area'] = le.fit_transform(data['Area'])
# data['Zone'] = le.fit_transform(data['Zone'])
# data['Time'] = le.fit_transform(data['Time'])
# data['People.Frequency'] = le.fit_transform(data['People.Frequency'])
# data['Is.Police_Station'] = le.fit_transform(data['Is.Police_Station'])
# data['Is.Bar'] = le.fit_transform(data['Is.Bar'])
# data['Class'] = le.fit_transform(data['Class'])
# print(le.classes_)
#display the initial records
data.head()

Area  Zone  Time  People.Frequency  Is.Police_Station  Is.Bar Class
0     1     0     2                 2                  1       0  Safe
1     1     0     0                 0                  1       0  Safe
2     1     0     1                 2                  1       0  Safe
3     1     0     3                 1                  1       0  Safe
4     1     1     2                 2                  0       0  Safe

In [ ]:
from sklearn.model_selection import train_test_split
y=data.Class
#y
x=data.drop('Class',axis=1)
x

Area  Zone  Time  People.Frequency  Is.Police_Station  Is.Bar
0       1     0     2                 2                  1       0
1       1     0     0                 0                  1       0
2       1     0     1                 2                  1       0
3       1     0     3                 1                  1       0
4       1     1     2                 2                  0       0
..    ...   ...   ...               ...                ...     ...
99      1    24     3                 1                  0       0
100     2    25     2                 0                  0       0
101     2    25     0                 2                  0       0
102     2    25     1                 0                  0       0
103     2    25     3                 1                  0       0

[104 rows x 6 columns]

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
x_train.head()

Area  Zone  Time  People.Frequency  Is.Police_Station  Is.Bar
30      2     7     1                 2                  0       0
100     2    25     2                 0                  0       0
69      0    17     0                 1                  0       0
44      2    11     2                 2                  0       1
42      1    10     1                 0                  1       0

In [ ]:
##Linear SVM- Using this!!

from sklearn.svm import SVC 

#Create a svm Classifier
svclassifier= SVC( kernel='linear')
#Train the model using the training sets
svclassifier.fit(x_train,y_train)

# Making Predictions

y_pred=svclassifier.predict(x_test)

In [ ]:
from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8571428571428571


In [ ]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='poly', degree=8, gamma='auto')  
# gamma is optional. But it gives a FutureWarning. To avoid it , specify
# gamma as 'auto' or 'scale'

svclassifier.fit(x_train, y_train)

# Making Predictions
# Now once we have trained the algorithm, 
# the next step is to make predictions on the test data.
y_pred = svclassifier.predict(x_test)  


# Evaluating the Algorithm
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))

# Note : Note the misclassification in 'virginica' species

[[13  3]
 [ 1  4]]
              precision    recall  f1-score   support

           0       0.93      0.81      0.87        16
           1       0.57      0.80      0.67         5

    accuracy                           0.81        21
   macro avg       0.75      0.81      0.77        21
weighted avg       0.84      0.81      0.82        21



In [ ]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='rbf', gamma='auto')  
svclassifier.fit(x_train, y_train) 

# Prediction and Evaluation
y_pred = svclassifier.predict(x_test)  

from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))  

# Note : Note the best performance thats 100% precise

[[16  0]
 [ 4  1]]
              precision    recall  f1-score   support

           0       0.80      1.00      0.89        16
           1       1.00      0.20      0.33         5

    accuracy                           0.81        21
   macro avg       0.90      0.60      0.61        21
weighted avg       0.85      0.81      0.76        21



In [ ]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='sigmoid', gamma='auto')  
svclassifier.fit(x_train, y_train)

# Prediction and Evaluation
y_pred = svclassifier.predict(x_test)  

from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))

# Note : Note the very poor perfomance from Sigmoid kernel

[[13  3]
 [ 5  0]]
              precision    recall  f1-score   support

           0       0.72      0.81      0.76        16
           1       0.00      0.00      0.00         5

    accuracy                           0.62        21
   macro avg       0.36      0.41      0.38        21
weighted avg       0.55      0.62      0.58        21



In [ ]:
from sklearn.tree import DecisionTreeClassifier  
classifier = DecisionTreeClassifier()  
classifier.fit(x_train, y_train)

# make predictions on the test data

y_pred = classifier.predict(x_test)  


# Evaluating the Algorithm
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))

[[15  1]
 [ 3  2]]
              precision    recall  f1-score   support

           0       0.83      0.94      0.88        16
           1       0.67      0.40      0.50         5

    accuracy                           0.81        21
   macro avg       0.75      0.67      0.69        21
weighted avg       0.79      0.81      0.79        21



In [ ]:
from sklearn.linear_model import LogisticRegression
# all parameters not specified are set to their defaults
logisticRegr = LogisticRegression()
logisticRegr.fit(x_train, y_train)
y_pred = logisticRegr.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))

[[15  1]
 [ 3  2]]
              precision    recall  f1-score   support

           0       0.83      0.94      0.88        16
           1       0.67      0.40      0.50         5

    accuracy                           0.81        21
   macro avg       0.75      0.67      0.69        21
weighted avg       0.79      0.81      0.79        21



In [ ]:
from sklearn.ensemble import RandomForestClassifier
classification = RandomForestClassifier(n_estimators=50, random_state=0)  
classification.fit(x_train, y_train)  
y_pred = classification.predict(x_test)  


# Evaluating the Algorithm
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred))

[[9 2]
 [3 7]]
              precision    recall  f1-score   support

           0       0.75      0.82      0.78        11
           1       0.78      0.70      0.74        10

    accuracy                           0.76        21
   macro avg       0.76      0.76      0.76        21
weighted avg       0.76      0.76      0.76        21

0.7619047619047619


In [ ]:
#####USING THISSSSSSS
from sklearn.svm import SVC 
import numpy as np
#Create a svm Classifier
svclassifier= SVC( kernel='linear')
#Train the model using the training sets
svclassifier.fit(x,y)
a=['Ramapuram','Aanandam Nagar','Morning','Medium','Yes','No']
a[0]=list(a[0].split("  "))
#print(a[0])
a[0]=enc.transform(a[0])
a[1]=enc1.transform(list(a[1].split("  ")))
a[2]=enc2.transform(list(a[2].split("  ")))
a[3]=enc3.transform(list(a[3].split("  ")))
a[4]=enc4.transform(list(a[4].split("  ")))
a[5]=enc5.transform(list(a[5].split("  ")))
a=np.concatenate( a, axis=0 )
print(a)
# Making Predictions
#print(x_test)
y_pred=svclassifier.predict([a])
print(y_pred)

[1 0 2 2 1 0]
['Safe']
